// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEgrVl_yDSnZpgS4GgzTvcCPTatkiFHjQ',
    appId: '1:802850984503:web:569706ee03c3a5ff8665b2',
    messagingSenderId: '802850984503',
    projectId: 'todo-5c8b9',
    authDomain: 'todo-5c8b9.firebaseapp.com',
    storageBucket: 'todo-5c8b9.firebasestorage.app',
    measurementId: 'G-4E1W87EESP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2ydFT0kRUw7js_g0HBkcU4m2a3rcV3cs',
    appId: '1:802850984503:android:6f1111581045c85b8665b2',
    messagingSenderId: '802850984503',
    projectId: 'todo-5c8b9',
    storageBucket: 'todo-5c8b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOn0K2M3FatNuGjajUnYDZlIF1XO2EZso',
    appId: '1:802850984503:ios:f1a9982812d548238665b2',
    messagingSenderId: '802850984503',
    projectId: 'todo-5c8b9',
    storageBucket: 'todo-5c8b9.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOn0K2M3FatNuGjajUnYDZlIF1XO2EZso',
    appId: '1:802850984503:ios:f1a9982812d548238665b2',
    messagingSenderId: '802850984503',
    projectId: 'todo-5c8b9',
    storageBucket: 'todo-5c8b9.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEgrVl_yDSnZpgS4GgzTvcCPTatkiFHjQ',
    appId: '1:802850984503:web:dae210be71149f9a8665b2',
    messagingSenderId: '802850984503',
    projectId: 'todo-5c8b9',
    authDomain: 'todo-5c8b9.firebaseapp.com',
    storageBucket: 'todo-5c8b9.firebasestorage.app',
    measurementId: 'G-1GBWF3LYCD',
  );
}
